services:
  _defaults:
    autowire: true
    autoconfigure: false

  NSaliu\TailDb\Service\Client: ~

  NSaliu\TailDb\EventSubscriber\ClientInterface:
    alias: NSaliu\TailDb\Service\Client

  NSaliu\TailDb\Service\Server: ~

  NSaliu\TailDb\Command\ServerInterface:
    alias: NSaliu\TailDb\Service\Server

  NSaliu\TailDb\EventSubscriber\DatabaseActivitySubscriber:
    arguments:
      $client: '@NSaliu\TailDb\EventSubscriber\ClientInterface'
    tags:
      - { name: 'doctrine.event_subscriber' }

  NSaliu\TailDb\Command\TailDbCommand:
    arguments:
      $server: '@NSaliu\TailDb\Command\ServerInterface'
    tags:
      - { name: 'console.command' }
